In [14]:
import math
import numpy as np

y=wx+b

In [36]:
def sigmoid(z):
    return 1/(1+pow(math.e,-z))
class Network():
    def __init__(self):
        self.w=-1
        self.b=2
    def y(self,x):
        return self.w * x + self.b

In [13]:
nat = Network()
nat.y(3)

5

In [34]:
w=np.random.randn(3,1)
w

array([[-0.22720189],
       [ 2.37162511],
       [ 0.15055899]])

In [37]:
class Network1():
    def __init__(self,n):
        self.w=np.random.randn(n,1)
        self.b=2
        self.n=n
    def y(self,x):
        return sigmoid(self.w * x + self.b)

In [38]:
nat = Network1(5)
print(nat.w)
print(nat.b)
nat.y([[1],[2],[3],[4],[5]])

[[ 0.79292961]
 [-1.42427364]
 [-0.49960042]
 [ 0.26516403]
 [-0.1897468 ]]
2


array([[0.94229256],
       [0.29973769],
       [0.622741  ],
       [0.95524036],
       [0.74101793]])

In [42]:
[[1],[2],[3],[4],[5]]

[[1], [2], [3], [4], [5]]

In [46]:
class Network2():
    def __init__(self,n,m):
        self.w=np.random.randn(m,n)
        self.b=np.random.randn(m,1)
        self.n=n
        self.m=m
    def y(self,x):
        return sigmoid(np.matmul(self.w, x )+ self.b)

In [47]:
nat = Network2(5,3)
print(nat.w)
print(nat.b)
nat.y([[1],[2],[3],[4],[5]])

[[-2.4240211  -1.41958593  0.13982756 -0.72078703  0.77801648]
 [-0.39175795  0.34368835  0.86690947 -0.46772299  1.6497625 ]
 [ 0.29260163  0.59670241  0.88744619 -0.53636444  0.2672696 ]]
[[-0.97136014]
 [-0.50009733]
 [ 0.75950926]]


array([[0.00809696],
       [0.99984535],
       [0.98367735]])

In [49]:
layer1 = Network2(5,3)
layer2 = Network2(3,1)
output=layer2.y(layer1.y([[1],[2],[3],[4],[5]]))

In [50]:
output

array([[0.90842426]])

In [51]:
class Network3():
    def __init__(self,n,m):
        self.w=np.random.randn(m,n)
        self.b=np.random.randn(m,1)
        self.n=n
        self.m=m
    def __call__(self,x):
        return sigmoid(np.matmul(self.w, x )+ self.b)

In [52]:
layer1 = Network3(5,3)
layer2 = Network3(3,1)
output=layer2(layer1([[1],[2],[3],[4],[5]]))

In [53]:
output

array([[0.8412023]])

In [ ]:
class Network4():
    def __init__(self,sizes):
        self.sizes=sizes
        w_list=[]
        for i in range(len(sizes)-1):
            w_list.append(np.random.randn(sizes[i+1],sizes[i]))
        self.w=np.random.randn(m,n)
        self.b=np.random.randn(m,1)
        self.n=n
        self.m=m
    def __call__(self,x):
        return sigmoid(np.matmul(self.w, x )+ self.b)